### ISSUE TITLE
Font Postcript name in TextBoxStyle - cannot make works

### ISSUE THREAD

**Issue by ilpadrinohack** [MatthiasValvekens/pyHanko#37]
Hi everyone. After updating pyhanko from 0.6.0 to 0.8.0, I am not able to choose the font for a visible signature. Only the "NotoSans-Regular" works. I have downloaded a lot of ttf unicode fonts , but always I get

Could not deduce PostScript name for font; only unicode-compatible encodings in the name table are supported. This is may code line:

`
tbst=TextBoxStyle(opentype.GlyphAccumulatorFactory('linux-biolinum-capitals-italic.ttf'))`

Also I have tried with:

`letra=SimpleFontEngine(writer.BasePdfFileWriter.get_subset_collection(self=root,   base_postscript_name='ArialMT-Bold'),  name='ArialMT-Bold',avg_width=1)`

with the result:

'_tkinter.tkapp' object has no attribute '_font_resources'

Don't know what to do.
Any helps will be appreciated

Thanks in advance

**Comment by MatthiasValvekens** [comment]
Hi,



Thanks for the report!

I’m currently out of town and I can’t provide a thorough workaround, but
I’m pretty sure I know what the problem is.

PyHanko reads the ‘name’ table in a TTF font to get the font’s canonical
PostScript name, and apparently your font doesn’t have any entries with a
UTF-16BE compatible encoding (you can thank Microsoft engineers for going
with UTF-16 instead of UTF-8). I assumed that that was standard practice in
TTF fonts nowadays, but apparently I was wrong.

 Now, chances are that the name is available in another entry that happens
to be encoded in an 8-bit (largely) ASCII-compatible encoding. I should
probably add that as a fallback, since it’ll work in a pretty large chunk
of cases. Perhaps adding a setting to GlyphAccumulatorFactory to manually
specify the PS base name would be a good thing as well.


I’ll take a closer look early next week, when I have access to my usual dev
environment. This is an interesting data point, thanks!

**Comment by ilpadrinohack** [comment]
Hi Matthias, thanks for your early reply. You are right, as always :).
In opentype.py, in `def _read_ps_name(tt: ttLib.TTFont) -> str:` function:

fails when:
            
           `if nr.encodingIsUnicodeCompatible():   
                        ps_name = nr.string.decode('utf-16be')` 

due to encoding setting.

Commenting the if statement, works only with a few fonts.

**Comment by MatthiasValvekens** [comment]
Yes, that’s more or less expected. If the entries are encoded using (some
superset of) ASCII, as I suspect they are, then trying to decode them as
UTF-16 won’t work, so commenting out the conditional alone isn’t enough. I
have a more robust fix in mind, but I can’t test it until tomorrow :)

**Comment by MatthiasValvekens** [comment]
I just pushed a (potential) fix (don't worry about the GH action "failure", that's Codecov complaining because I deleted a line of covered code). Apparently `fontTools` already solved this problem, it was a matter of calling `.toUnicode()` on the name records retrieved from `fontTools` directly. Do you still see an error with name decoding?

Note: It's somewhat likely that other issues will appear with "traditional" (i.e. non-OTF) TTF fonts. I'm not much of a font expert, so I'm not aware of the "quirks" that real-world fonts can have, and it's possible that I messed up some font metric computations here and there. Please create new issues for those (if you find any), and if possible, try to reproduce them with fonts that are permissively licensed (e.g. SIL OFL or equivalent). The licensing thing is a necessity for regression tests. :)

**Comment by ilpadrinohack** [comment]
Fixed. You are great. Tested with different fonts and all of them working.

Great job Matthias.
Thanks in advance

**Comment by MatthiasValvekens** [comment]
Happy to help. Thanks for reporting back!
